language: clojure
lein: 2.9.1
jdk:
  - openjdk8
  - openjdk11
env:
  - ADDITIONAL_ARGS='with-profile fips'
  - ADDITIONAL_ARGS=''
script: lein $ADDITIONAL_ARGS test :all
notifications:
  email: false
